### ISSUE TITLE
Cannot load new lesson into antidote-selfmedicate

### ISSUE THREAD

**Issue by blinklet** [nre-learning/antidote-selfmedicate#24]
I created a new lesson, similar to other lessons. I placed it in the `~/nrelabs-curriculum/lessons/fundamentals` directory. I named the new lesson directory `lesson-100-frr`.

When I run the `selfmedicate.sh --reload` command, the lessons do not appear in the web interface.

I looked in the minikube VM:

```
minikube ssh
```

And looked in the lesson directory

```
cd /antidote/lessons/fundamentals/
```

And I can see the lesson directory was copied over to the VM:

```
ls
lesson-100-frr	lesson-16-jinja  lesson-19-restapis  lesson-23-linux
lesson-14-yaml	lesson-17-git	 lesson-22-python
```

So, is there something I need to update elsewhere to add a lesson and test it? What am I missing?

**Comment by blinklet** [comment]
I just copied the Linux Basics lesson, then edited the `lesson.meta.yaml` file to change the lesson name and lesson number and slug so I don't think there should be an issue with the lesson formatting.

```
cp -r lesson-23-linux/ lesson-100-frr/
cd lesson-100-frr
```
Then I edited the `lesson.meta.yaml` file so it is now:

```
---
lessonName: Frr
lessonId: 100
category: fundamentals
tier: prod
tags:
- linux
- bash
description: Being able to work with Linux and the Bash shell is becoming an increasingly important skill in the world of Network Reliability Engineering. In this lesson, we'll cover the basics of a Linux-based system, and get you acquainted with the Bash shell.
slug: FRR

utilities:
- name: linux1
  image: antidotelabs/utility

stages:
  - id: 1
    description: Using the Bash Shell
```

Then I ran the `selfmedicate.sh --reload` command.

The new lesson does not appear after I refresh the page on the web interface.
